fork_me_ribbon_url: https://github.com/coderefinery/reproducible-research
baseurl: "/reproducible-research"
title: "Reproducible research"

source: .
destination: ./_site
layouts_dir: ./jekyll-common/layouts
includes_dir: ./jekyll-common/includes

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

include: ['jekyll-common/pages']

collections:
  episodes:
    output: true
    permalink: /:name/
